### ISSUE TITLE
NodeJs学习

### ISSUE THREAD

**Issue by caohuilin** [caohuilin/Project#12]

**Comment by caohuilin** [comment]
- egg 文档熟悉 https://eggjs.org/zh-cn/
 - Mongoose 文档熟悉 http://mongoosejs.com/docs
 - [x] 运行example 项目，熟悉源码
 - [x] 搭建todo MVC 项目，实现添加，删除，查找，完成等功能
 - [ ] API 单元测试
 - [x] 搭建todo MVC 前端项目
 - [x] 前后端API联调
 - [ ] API文档
 - [x] 完善前端样式和流程

**Comment by caohuilin** [comment]
https://github.com/caohuilin/egg-Todo-MVC/pull/1

**Comment by wangkechun** [comment]
https://swagger.io/swagger-editor/ api文档

**Comment by caohuilin** [comment]
https://github.com/caohuilin/egg-front-todo/commit/da1032b3f9a83badb950ebd71a6840d55c4fcc09
